# Generated by Django 2.2.1 on 2019-06-09 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190609_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='borrow_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
