# Generated by Django 2.2.1 on 2019-06-09 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20190609_1959'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ratings',
            new_name='Rating_Users',
        ),
    ]
