# Generated by Django 2.2.1 on 2019-06-09 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20190609_2000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating_Users',
        ),
    ]
