# Generated by Django 2.2.1 on 2019-06-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_delete_rating_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='rating_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
