# Generated by Django 2.2.1 on 2019-06-14 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20190614_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='borrow_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
