# Generated by Django 2.2.1 on 2019-06-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating_total',
        ),
        migrations.RemoveField(
            model_name='book',
            name='rating_users',
        ),
    ]
